package util
 const val MENU_SALES=1
const val MENU_CARS=2
const val MENU_PAYMENTS=3
const val MENU_ORDERS=4
const val MENU_EXIT=5


const val CATEGORY_PRODUCT_ADHESIVOS=1
const val CATEGORY_PRODUCT_CEMENTOMORTEROSYCOMPLEMENTOS=2
const val CATEGORY_PRODUCT_HERRAMIENTASMANUALES=3
const val CATEGORY_PRODUCT_CHAPASPARAPUERTASYCERRADURAS=4
const val CATEGORY_PRODUCT_ACCESORIOSPARAPUERTASYVENTANAS=5