package util.constants

const val MENU_ETAPA_DE_ARRIBO = 1
const val MENU_VER_ARRIBOS = 2
const val MENU_ETAPA_DE_DESARME = 3
const val MENU_VER_DESARMES = 4
const val MENU_REVISION_Y_REPARACION=5
const val MENU_VER_REVISION_Y_REPARACION=6

const val TIEMPO_MAXIMO_PARA_ARRIBO = 1200